### ISSUE TITLE
No bonus between 3rd and 4th periods?

### ISSUE THREAD

**Issue by TovarishFin** [ethorse/ico#1]
It seems like the the 4th period of time is missing ` - 1 days` in `HorseTokenCrowdsale.sol`

```function setBonusPrice() public constant returns (uint256 bonus) {
        require(isCrowdSaleSetup);
        require(fundingStartTime + p1_duration <= p2_start );
        if (now >= fundingStartTime && now <= fundingStartTime + p1_duration) { // Phase-1 Bonus    +100% = 20,000 HORSE  = 1 ETH
            bonus = 10000;
        } else if (now > p2_start && now <= p2_start + 1 days ) { // Phase-2 day-1 Bonus +50% = 15,000 HORSE = 1 ETH
            bonus = 5000;
        } else if (now > p2_start + 1 days && now <= p2_start + 1 weeks - 1 days) { // Phase-2 week-1 Bonus +20% = 12,000 HORSE = 1 ETH
            bonus = 2000;
        } else if (now > p2_start + 1 weeks && now <= p2_start + 2 weeks ) { // Phase-2 week-2 Bonus +10% = 11,000 HORSE = 1 ETH
            bonus = 1000;
        } else if (now > p2_start + 2 weeks && now <= fundingEndTime ) { // Phase-2 week-3& week-4 Bonus +0% = 10,000 HORSE = 1 ETH
            bonus = 0;
        } else {
            revert();
        }
    }```

**Comment by ethorse** [comment]
The Phase-2 runs for 1 week (7days). The day 1 of phase-2 alone has a 50% bonus and rest of the phase-2 20% bonus. 
In 2nd period it just covers 1 day.
In 3rd period `p2_start + 1 weeks - 1 days` converts to `p2_start + 6 days`.
combining 1 day in 2nd period and 6 days in 3rd period is 7 days(1 week)
So in the 4th period the offset would be `p2_start + 1 week`

**Comment by TovarishFin** [comment]
There still is a 1 day gap in there where no bonuses are being given out... no? Perhaps I am misreading?

**Comment by ethorse** [comment]
Nope! I am afraid you are misreading. The only period when there is no bonus is from 2nd week of phase-2

**Comment by TovarishFin** [comment]
Yes... this is exactly what I meant... but from the sound of your response, this is intentional... alright.

**Comment by ethorse** [comment]
@TovarishFin Apologies I misinterpreted what you were trying to say before. The bug you were trying to report was indeed true. I am reopening this issue!

**Comment by ethorse** [comment]
Users trying to contribute during the Phase-2 week-2 last day will face issues. Since the contribution time won't fit in any of the if clause, the transactions will be reverted. 
```
else {
    revert();
}
```
The impact of this issue is low even though the likelihood of occurrence is high. The bug is considered medium severity. 
Appreciate you taking the time to review the code. We would like to reward you with $300. Please provide your ETH address. Thank you.
