### ISSUE TITLE
refund should burn HorseToken balance

### ISSUE THREAD

**Issue by TovarishFin** [ethorse/ico#2]
It seems rather messy to leave the HorseToken balances alone if the funding goal did not go through. Given you can simply pause the token and leave it be... but it seems to me that it would be much more clean to burn the balance when a refund is done. A simple burn function which only the crowdsale contract can would take care of this.

**Comment by ethorse** [comment]
The HORSE token itself is a Burnable Token. Though its an option to burn to the token when refunding, it won't affect in any way. In the scenario of a refund, the crowdsale wouldn't have been successful. This would essentially make the tokens of no value. If the up to the user to do what they want with the voided tokens.
