### ISSUE TITLE
Users don't receive expected bonus on 7th day of week 1

### ISSUE THREAD

**Issue by janbro** [ethorse/ico#3]
```
       if (now >= fundingStartTime && now <= fundingStartTime + p1_duration) { // Phase-1 Bonus    +100% = 20,000 HORSE  = 1 ETH
            bonus = 10000;
        } else if (now > p2_start && now <= p2_start + 1 days ) { // Phase-2 day-1 Bonus +50% = 15,000 HORSE = 1 ETH
            bonus = 5000;
        } else if (now > p2_start + 1 days && now <= p2_start + 1 weeks - 1 days) { // Phase-2 week-1 Bonus +20% = 12,000 HORSE = 1 ETH
            bonus = 2000;
        } else if (now > p2_start + 1 weeks && now <= p2_start + 2 weeks ) { // Phase-2 week-2 Bonus +10% = 11,000 HORSE = 1 ETH
            bonus = 1000;
        } else if (now > p2_start + 2 weeks && now <= fundingEndTime ) { // Phase-2 week-3& week-4 Bonus +0% = 10,000 HORSE = 1 ETH
            bonus = 0;
        } else {
            revert();
        }
```
It seems phase 2 week 2 is starting with a day delay after phase 2 week 1 is ended. Phase 2 week 1 only lasts a total of 6 days. Is this intended behaviour? Also, with your chained ifs, you can check only if you're in phase 2 then check the upper limit bound of time. This makes the phase transitions easier since you don't have to make sure the lower bound of the next if is exactly when the previous phase ends. I've included a fix below.

```
       if (now >= fundingStartTime && now <= fundingStartTime + p1_duration) { // Phase-1 Bonus    +100% = 20,000 HORSE  = 1 ETH
            bonus = 10000;
        } else if (now > p2_start && now <= p2_start + 1 days ) { // Phase-2 day-1 Bonus +50% = 15,000 HORSE = 1 ETH
            bonus = 5000;
        } else if (now > p2_start && now <= p2_start + 1 weeks) { // Phase-2 week-1 Bonus +20% = 12,000 HORSE = 1 ETH
            bonus = 2000;
        } else if (now > p2_start && now <= p2_start + 2 weeks ) { // Phase-2 week-2 Bonus +10% = 11,000 HORSE = 1 ETH
            bonus = 1000;
        } else if (now > p2_start && now <= fundingEndTime ) { // Phase-2 week-3& week-4 Bonus +0% = 10,000 HORSE = 1 ETH
            bonus = 0;
        } else {
            revert();
        }
```

**Comment by ethorse** [comment]
Yes, you got it right and that is the intended behavior. The phase-2 week-1 has a total of 7 days. The phase-2 week-1 day-1 alone has a higher bonus than the rest of the week. That's the reason it lasts only for 6 days. 
Also, your modified code serves the purpose. Checking for the lower bound again doesn't make much difference.

**Comment by janbro** [comment]
So the one day delay of no bonus is intended? Say p2_start was on the 10th of the month at 00:01. The p2 day 1 bonus would be active until the 10 + 1 days, the 11th. The p2 week 1 bonus would be active until 10 + 1 weeks - 1 days, the 16th (10 + 7 -1). The p2 week 2 bonus would then not be active until now > 10 + 1 weeks, the 17th. So there is the time between 16th 00:01 to the 17th 00:01 where setBonusPrice is reverting.

**Comment by janbro** [comment]
1 [day](http://solidity.readthedocs.io/en/develop/units-and-global-variables.html) in solidity is an alias for 60\*60\*24, so the <= comparison wouldn't hold true for all of the last day of week 1.

**Comment by ethorse** [comment]
From the if clause it is indeed true that contributors trying to buy tokens during Phase-2 Week-2 last day will face issues. This issue was already raised by another user in issue #1
